import DownloadOutlined from '@mui/icons-material/DownloadOutlined';
import Button from '@mui/material/Button';
import { useCsvExport } from '../hooks/useCsvExport';

// Downloads the full scrape history (GET /api/export.csv, generated by the server). Used on the dashboard and the
// Scrape Logs page.
export function ExportCsvButton({ variant = 'contained' }: { variant?: 'contained' | 'outlined' }) {
  const exportCsv = useCsvExport();
  return (
    <Button variant={variant} startIcon={<DownloadOutlined />} loading={exportCsv.isPending} loadingPosition="start" onClick={() => exportCsv.mutate()}>
      Export CSV
    </Button>
  );
}
