import type { ApiErrorBody } from '../../types/api';
import { ApiError, api } from './client';

export type CsvExport = { blob: Blob; filename: string };

// GET /api/export.csv: every finished attempt, generated by the server. The file is fetched here (not opened as a
// link) so the page can show progress and failures.
export async function downloadExport(): Promise<CsvExport> {
  // Resolve every status: an error body arrives as a Blob, which the shared error handler cannot read.
  const response = await api.get<Blob>('/export.csv', { responseType: 'blob', validateStatus: () => true });
  if (response.status !== 200) throw await exportError(response.status, response.data);
  return { blob: response.data, filename: exportFilename(response.headers['content-disposition'], new Date()) };
}

// The server names the file in Content-Disposition, but a cross-origin page can only read that header when the API
// exposes it, which it does not; the fallback uses the server's own naming pattern.
export function exportFilename(contentDisposition: unknown, now: Date): string {
  const match = typeof contentDisposition === 'string' ? /filename="([^"]+)"/.exec(contentDisposition) : null;
  return match?.[1] ?? `pricepulse-scrape-history-${now.toISOString().replace(/[:.]/g, '-')}.csv`;
}

export async function exportError(status: number, body: Blob): Promise<ApiError> {
  try {
    const { error } = JSON.parse(await body.text()) as ApiErrorBody;
    return new ApiError(status, error.code, error.message, error.details);
  } catch {
    return new ApiError(status, 'export_failed', `The export failed (HTTP ${status})`);
  }
}
